Repository rajsagare14/WhatsappWebAutomation, pull requests merged in 2022-10, with the labels that each got.

#9 Updated README.md
  README.md
Labels: documentation, hacktoberfest, hactoberfest2022, hacktoberfest-accepted

#12 Added spam bot code
  README.md
  spam_bot.py
Labels: enhancement, help wanted, good first issue, hacktoberfest, hactoberfest2022, updates, hacktoberfest-accepted

#13 added the code for whatsapp automation
  automation.py
Labels: enhancement, hacktoberfest, hactoberfest2022, updates, hacktoberfest-accepted
